### ISSUE TITLE
nacos1.2.0加了权限认证，sdk可否跟上

### ISSUE THREAD

**Issue by oneinstack** [olivetree123/pynacos-sdk#2]
接口：POST /nacos/v1/auth/users/login?username=xxx&password=yyy

**Comment by olivetree123** [comment]
官方文档还没有看到这个接口的说明

**Comment by oneinstack** [comment]
参考：https://nacos.io/en-us/blog/nacos%201.2.0%20guide.html

**Comment by olivetree123** [comment]
OK，会尽快安排上

**Comment by olivetree123** [comment]
已完成 #3
